project:
  type: book
  title: Statistical Computing
  output-dir: _site
  

website: 
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: PracOne.qmd
        text: Second Page
      - href: PracTwo.qmd
        text: Third Page
      - href: PracDayFour.qmd
        text: Fourth Page
        
        
book: 
  chapters: 
    - index.qmd
    - PracOne.qmd
    - PracTwo.qmd
    - PracDayFour.qmd

format: 
  html: 
    toc: true
    toc-depth: 5
    toc-location: left
    theme: cosmo
